/**
 * Card artist data and URL mappings
 */

export const CARD_ARTISTS = {
    '2♠': 'Mattias Adolfsson',
    '3♠': 'Teagan White',
    '4♠': 'Serial Cut™',
    '5♠': 'Musketon',
    '6♠': 'Fernando Volken Togni',
    '7♠': 'Muxxi',
    '8♠': 'Gary Fernández',
    '9♠': 'Anton Repponen',
    '10♠': 'Bicicleta Sem Freio',
    'J♠': 'Seb Niark1',
    'Q♠': 'David Mack',
    'K♠': 'Yulia Brodskaya',
    'A♠': 'Iain Macarthur',

    '2♥': 'Peter Tarka',
    '3♥': 'Mercedes deBellard',
    '4♥': 'Ruben Ireland',
    '5♥': 'Aitch',
    '6♥': 'Javier Medellin Puyou',
    '7♥': 'Felix LaFlamme',
    '8♥': 'Raul Urias',
    '9♥': 'Carlos Lerma',
    '10♥': 'Caramelaw',
    'J♥': 'Steve Simpson',
    'Q♥': 'Conrad Roset',
    'K♥': 'Sara Blake',
    'A♥': 'Mr. Kone',

    '2♦': 'Yema Yema',
    '3♦': 'Carne Griffiths',
    '4♦': 'Peter Olschinsky',
    '5♦': 'Fab Ciraolo',
    '6♦': 'VASAVA',
    '7♦': 'Matt W. Moore',
    '8♦': 'Jthree Concepts',
    '9♦': 'Pirecco',
    '10♦': 'Lei Melendres',
    'J♦': 'Newfren',
    'Q♦': 'agnes-cecile',
    'K♦': 'Saturno (THE CREATTER)',
    'A♦': 'Jordan Debney',

    '2♣': 'Tang Yau Hoong',
    '3♣': 'Fernando Chamarelli',
    '4♣': 'MUTI',
    '5♣': 'Valerie Ann Chua',
    '6♣': 'Tobias van Schneider',
    '7♣': 'Krzysztof CHKN Nowak',
    '8♣': 'El Grand Chamaco',
    '9♣': 'Chuck Anderson',
    '10♣': 'Hey',
    'J♣': 'Bakea',
    'Q♣': 'Ise Ananphada',
    'K♣': 'James White',
    'A♣': 'Andreas Preis',

    JOKER_1: 'Mike Friedrich',
    JOKER_2: 'Joshua Davis'
};

export const ARTIST_URL_SLUGS = {
    'Mattias Adolfsson': 'mattias-adolfsson',
    'Teagan White': 'teagan-white',
    'Serial Cut™': 'serial-cut',
    Musketon: 'musketon',
    'Fernando Volken Togni': 'fernando-volken-togni',
    Muxxi: 'muxxi',
    'Gary Fernández': 'gary-fernández',
    'Anton Repponen': 'anton-repponen',
    'Bicicleta Sem Freio': 'bicicleta-sem-freio',
    'Seb Niark1': 'seb-niark1',
    'David Mack': 'david-mack',
    'Yulia Brodskaya': 'yulia-brodskaya',
    'Iain Macarthur': 'iain-macarthur',
    'Peter Tarka': 'peter-tarka',
    'Mercedes deBellard': 'mercedes-debellard',
    'Ruben Ireland': 'ruben-ireland',
    Aitch: 'aitch',
    'Javier Medellin Puyou': 'jilipollo',
    'Felix LaFlamme': 'felix-laflamme',
    'Raul Urias': 'raul-urias',
    'Carlos Lerma': 'carlos-lerma',
    Caramelaw: 'caramelaw',
    'Steve Simpson': 'steve-simpson',
    'Conrad Roset': 'conrad-roset',
    'Sara Blake': 'sara-blake',
    'Mr. Kone': 'mr-kone',
    'Yema Yema': 'yema-yema',
    'Carne Griffiths': 'carne-griffiths',
    'Peter Olschinsky': 'peter-olschinsky',
    'Fab Ciraolo': 'fab-ciraolo',
    VASAVA: 'vasava',
    'Matt W. Moore': 'matt-w.-moore',
    'Jthree Concepts': 'jthree-concepts',
    Pirecco: 'pirecco',
    'Lei Melendres': 'lei-melendres',
    Newfren: 'newfren',
    'agnes-cecile': 'agnes-cecile',
    'Saturno (THE CREATTER)': 'saturno',
    'Jordan Debney': 'jordan-debney',
    'Tang Yau Hoong': 'tang-yau-hoong',
    'Fernando Chamarelli': 'fernando-chamarelli',
    MUTI: 'muti',
    'Valerie Ann Chua': 'valerie-ann-chua',
    'Tobias van Schneider': 'tobias-van-schneider',
    'Krzysztof CHKN Nowak': 'krzysztof-chkn-nowak',
    'El Grand Chamaco': 'el-grand-chamaco',
    'Chuck Anderson': 'chuck-anderson',
    Hey: 'hey',
    Bakea: 'bakea',
    'Ise Ananphada': 'ise-ananphada',
    'James White': 'james-white',
    'Andreas Preis': 'andreas-preis',
    'Mike Friedrich': 'mike-friedrich',
    'Joshua Davis': 'joshua-davis'
};

export const CARD_IMAGE_FILENAMES = {
    '2♠': '2-of-spades-mattias-adolfsson.jpg?2',
    '3♠': '3-of-spades-teagan-white.jpg?2',
    '4♠': '4-of-spades-serial-cut.jpg?2',
    '5♠': '5-of-spades-musketon.jpg?2',
    '6♠': '6-of-spades-fernando-volken-togni.jpg?2',
    '7♠': '7-of-spades-muxxi.jpg?2',
    '8♠': '8-of-spades-gary-fernandez.jpg?2',
    '9♠': '9-of-spades-anton-repponen.jpg?2',
    '10♠': '10-of-spades-bicicleta-sem-freio.jpg?2',
    'J♠': 'jack-of-spades-seb-niark1.jpg?2',
    'Q♠': 'queen-of-spades-david-mack.jpg?2',
    'K♠': 'king-of-spades-yulia-brodskaya.jpg?2',
    'A♠': 'ace-of-spades-iain-macarthur.jpg?2',

    '2♥': '2-of-hearts-peter-tarka.jpg?2',
    '3♥': '3-of-hearts-mercedes-debellard.jpg?2',
    '4♥': '4-of-hearts-ruben-ireland.jpg?2',
    '5♥': '5-of-hearts-aitch.jpg?2',
    '6♥': '6-of-hearts-javier-medellin-puyou.jpg?2',
    '7♥': '7-of-hearts-felix-laflamme.jpg?2',
    '8♥': '8-of-hearts-raul-urias.jpg?2',
    '9♥': '9-of-hearts-carlos-lerma.jpg?2',
    '10♥': '10-of-hearts-caramelaw.jpg?2',
    'J♥': 'jack-of-hearts-steve-simpson.jpg?2',
    'Q♥': 'queen-of-hearts-conrad-roset.jpg?2',
    'K♥': 'king-of-hearts-sara-blake.jpg?2',
    'A♥': 'ace-of-hearts-mr-kone.jpg?2',

    '2♦': '2-of-diamonds-yemayema.jpg?2',
    '3♦': '3-of-diamonds-carne-griffiths.jpg',
    '4♦': '4-of-diamonds-peter-olschinsky.jpg?2',
    '5♦': '5-of-diamonds-fab-ciraolo.jpg?2',
    '6♦': '6-of-diamonds-vasava.jpg?2',
    '7♦': '7-of-diamonds-matt-w-moore.jpg?2',
    '8♦': '8-of-diamonds-jthree-concepts.jpg?2',
    '9♦': '9-of-diamonds-pirecco.jpg?2',
    '10♦': '10-of-diamonds-lei-melendres.jpg?2',
    'J♦': 'jack-of-diamonds-newfren.jpg?2',
    'Q♦': 'queen-of-diamonds-agnes-cecile.jpg?2',
    'K♦': 'king-of-diamonds-saturno-the-creatter.jpg?2',
    'A♦': 'ace-of-diamonds-jordan-debney.jpg?2',

    '2♣': '2-of-clubs-tang-yau-hoong.jpg?2',
    '3♣': '3-of-clubs-fernando-chamarelli.jpg?2',
    '4♣': '4-of-clubs-muti.jpg?2',
    '5♣': '5-of-clubs-valerie-ann-chua.jpg?2',
    '6♣': '6-of-clubs-tobias-van-schneider.jpg?2',
    '7♣': '7-of-clubs-krzysztof-nowak.jpg?2',
    '8♣': '8-of-clubs-el-grand-chamaco.jpg?2',
    '9♣': '9-of-clubs-chuck-anderson.jpg?2',
    '10♣': '10-of-clubs-hey.jpg?2',
    'J♣': 'jack-of-clubs-bakea.jpg?2',
    'Q♣': 'queen-of-clubs-ise-ananphada.jpg?2',
    'K♣': 'king-of-clubs-james-white.jpg?2',
    'A♣': 'ace-of-clubs-andreas-preis.jpg?2',

    JOKER: 'joker-mike-friedrich.jpg?2',
    JOKER_2: 'joker-joshua-davis.jpg?2'
};
