/**
 * Playing Arts Edition configurations
 * Each edition has its own set of card images, artists, and URLs
 */

export const EDITIONS = {
    one: {
        id: 'one',
        name: 'Edition One',
        baseUrl: 'https://s3.amazonaws.com/img.playingarts.com/one-small-hd/',
        infoUrl: 'https://playingarts.com/one/',
        backsideImage: '_backside-evgeny-kiselev.jpg?2',
        cardFilenames: {
            '2♠': '2-of-spades-mattias-adolfsson.jpg',
            '3♠': '3-of-spades-teagan-white.jpg',
            '4♠': '4-of-spades-serial-cut.jpg',
            '5♠': '5-of-spades-musketon.jpg',
            '6♠': '6-of-spades-fernando-volken-togni.jpg',
            '7♠': '7-of-spades-muxxi.jpg',
            '8♠': '8-of-spades-gary-fernandez.jpg',
            '9♠': '9-of-spades-anton-repponen.jpg',
            '10♠': '10-of-spades-bicicleta-sem-freio.jpg',
            'J♠': 'jack-of-spades-seb-niark1.jpg',
            'Q♠': 'queen-of-spades-david-mack.jpg',
            'K♠': 'king-of-spades-yulia-brodskaya.jpg',
            'A♠': 'ace-of-spades-iain-macarthur.jpg',
            '2♥': '2-of-hearts-peter-tarka.jpg',
            '3♥': '3-of-hearts-mercedes-debellard.jpg',
            '4♥': '4-of-hearts-ruben-ireland.jpg',
            '5♥': '5-of-hearts-aitch.jpg',
            '6♥': '6-of-hearts-javier-medellin-puyou.jpg',
            '7♥': '7-of-hearts-felix-laflamme.jpg',
            '8♥': '8-of-hearts-raul-urias.jpg',
            '9♥': '9-of-hearts-carlos-lerma.jpg',
            '10♥': '10-of-hearts-caramelaw.jpg',
            'J♥': 'jack-of-hearts-steve-simpson.jpg',
            'Q♥': 'queen-of-hearts-conrad-roset.jpg',
            'K♥': 'king-of-hearts-sara-blake.jpg',
            'A♥': 'ace-of-hearts-mr-kone.jpg',
            '2♦': '2-of-diamonds-yemayema.jpg',
            '3♦': '3-of-diamonds-carne-griffiths.jpg',
            '4♦': '4-of-diamonds-peter-olschinsky.jpg',
            '5♦': '5-of-diamonds-fab-ciraolo.jpg',
            '6♦': '6-of-diamonds-vasava.jpg',
            '7♦': '7-of-diamonds-matt-w-moore.jpg',
            '8♦': '8-of-diamonds-jthree-concepts.jpg',
            '9♦': '9-of-diamonds-pirecco.jpg',
            '10♦': '10-of-diamonds-lei-melendres.jpg',
            'J♦': 'jack-of-diamonds-newfren.jpg',
            'Q♦': 'queen-of-diamonds-agnes-cecile.jpg',
            'K♦': 'king-of-diamonds-saturno-the-creatter.jpg',
            'A♦': 'ace-of-diamonds-jordan-debney.jpg',
            '2♣': '2-of-clubs-tang-yau-hoong.jpg',
            '3♣': '3-of-clubs-fernando-chamarelli.jpg',
            '4♣': '4-of-clubs-muti.jpg',
            '5♣': '5-of-clubs-valerie-ann-chua.jpg',
            '6♣': '6-of-clubs-tobias-van-schneider.jpg',
            '7♣': '7-of-clubs-krzysztof-nowak.jpg',
            '8♣': '8-of-clubs-el-grand-chamaco.jpg',
            '9♣': '9-of-clubs-chuck-anderson.jpg',
            '10♣': '10-of-clubs-hey.jpg',
            'J♣': 'jack-of-clubs-bakea.jpg',
            'Q♣': 'queen-of-clubs-ise-ananphada.jpg',
            'K♣': 'king-of-clubs-james-white.jpg',
            'A♣': 'ace-of-clubs-andreas-preis.jpg',
            JOKER: 'joker-mike-friedrich.jpg',
            JOKER_2: 'joker-joshua-davis.jpg'
        },
        cardArtists: {
            '2♠': 'Mattias Adolfsson',
            '3♠': 'Teagan White',
            '4♠': 'Serial Cut™',
            '5♠': 'Musketon',
            '6♠': 'Fernando Volken Togni',
            '7♠': 'Muxxi',
            '8♠': 'Gary Fernández',
            '9♠': 'Anton Repponen',
            '10♠': 'Bicicleta Sem Freio',
            'J♠': 'Seb Niark1',
            'Q♠': 'David Mack',
            'K♠': 'Yulia Brodskaya',
            'A♠': 'Iain Macarthur',
            '2♥': 'Peter Tarka',
            '3♥': 'Mercedes deBellard',
            '4♥': 'Ruben Ireland',
            '5♥': 'Aitch',
            '6♥': 'Javier Medellin Puyou',
            '7♥': 'Felix LaFlamme',
            '8♥': 'Raul Urias',
            '9♥': 'Carlos Lerma',
            '10♥': 'Caramelaw',
            'J♥': 'Steve Simpson',
            'Q♥': 'Conrad Roset',
            'K♥': 'Sara Blake',
            'A♥': 'Mr. Kone',
            '2♦': 'Yema Yema',
            '3♦': 'Carne Griffiths',
            '4♦': 'Peter Olschinsky',
            '5♦': 'Fab Ciraolo',
            '6♦': 'VASAVA',
            '7♦': 'Matt W. Moore',
            '8♦': 'Jthree Concepts',
            '9♦': 'Pirecco',
            '10♦': 'Lei Melendres',
            'J♦': 'Newfren',
            'Q♦': 'agnes-cecile',
            'K♦': 'Saturno (THE CREATTER)',
            'A♦': 'Jordan Debney',
            '2♣': 'Tang Yau Hoong',
            '3♣': 'Fernando Chamarelli',
            '4♣': 'MUTI',
            '5♣': 'Valerie Ann Chua',
            '6♣': 'Tobias van Schneider',
            '7♣': 'Krzysztof CHKN Nowak',
            '8♣': 'El Grand Chamaco',
            '9♣': 'Chuck Anderson',
            '10♣': 'Hey',
            'J♣': 'Bakea',
            'Q♣': 'Ise Ananphada',
            'K♣': 'James White',
            'A♣': 'Andreas Preis',
            JOKER_1: 'Mike Friedrich',
            JOKER_2: 'Joshua Davis'
        },
        // URL slug overrides for artists where filename doesn't match website URL
        cardArtistUrls: {
            '8♠': 'gary-fernández',
            '6♥': 'jilipollo',
            '2♦': 'yema-yema',
            '7♦': 'matt-w.-moore',
            'K♦': 'saturno',
            '7♣': 'krzysztof-chkn-nowak'
        }
    },
    two: {
        id: 'two',
        name: 'Edition Two',
        baseUrl: 'https://s3.amazonaws.com/img.playingarts.com/two-small-hd/',
        infoUrl: 'https://playingarts.com/two/',
        backsideImage: '_backside-danny-ivan.jpg',
        cardFilenames: {
            '2♠': '2-of-spades-fictive-artist.jpg',
            '3♠': '3-of-spades-steven-wilson.jpg',
            '4♠': '4-of-spades-anton-repponen.jpg',
            '5♠': '5-of-spades-gabriel-moreno.jpg',
            '6♠': '6-of-spades-zansky.jpg',
            '7♠': '7-of-spades-chocotoy.jpg',
            '8♠': '8-of-spades-rubens-scarelli.jpg',
            '9♠': '9-of-spades-pichet-rujivararat.jpg',
            '10♠': '10-of-spades-marcelo-schultz.jpg',
            'J♠': 'jack-of-spades-peter-donnelly.jpg',
            'Q♠': 'queen-of-spades-zso-sara-blake.jpg',
            'K♠': 'king-of-spades-yeaaah-studio.jpg',
            'A♠': 'ace-of-spades-ars-thanea.jpg',
            '2♥': '2-of-hearts-maria-gronlund.jpg',
            '3♥': '3-of-hearts-oscar-ramos.jpg',
            '4♥': '4-of-hearts-steve-simpson.jpg',
            '5♥': '5-of-hearts-charles-williams.jpg',
            '6♥': '6-of-hearts-freak-city.jpg',
            '7♥': '7-of-hearts-antoni-tudisco.jpg',
            '8♥': '8-of-hearts-van-orton-design.jpg',
            '9♥': '9-of-hearts-irina-vinnik.jpg',
            '10♥': '10-of-hearts-david-sossella.jpg',
            'J♥': 'jack-of-hearts-julian-ardila.jpg',
            'Q♥': 'queen-of-hearts-orlando-arocena.jpg',
            'K♥': 'king-of-hearts-yoaz.jpg',
            'A♥': 'ace-of-hearts-studio-blup.jpg',
            '2♦': '2-of-diamonds-jon-lau.jpg',
            '3♦': '3-of-diamonds-zipeng-zhu.gif',
            '4♦': '4-of-diamonds-foreal.jpg',
            '5♦': '5-of-diamonds-patrick-seymour.jpg',
            '6♦': '6-of-diamonds-ian-jepson.jpg',
            '7♦': '7-of-diamonds-sakiroo.jpg',
            '8♦': '8-of-diamonds-mathis-rekowski.jpg',
            '9♦': '9-of-diamonds-viktor-miller-gausa.jpg',
            '10♦': '10-of-diamonds-kerby-rosanes.jpg',
            'J♦': 'jack-of-diamonds-stavros-damos.jpg',
            'Q♦': 'queen-of-diamonds-pablo-jurado-ruiz.jpg',
            'K♦': 'king-of-diamonds-alexis-marcou.jpg',
            'A♦': 'ace-of-diamonds-joshua-davis.jpg',
            '2♣': '2-of-clubs-jonathan-calugi.jpg',
            '3♣': '3-of-clubs-tamer-koseli.jpg',
            '4♣': '4-of-clubs-jeff-rogers.jpg',
            '5♣': '5-of-clubs-mikey-burton.jpg',
            '6♣': '6-of-clubs-migthy-short.jpg',
            '7♣': '7-of-clubs-adhemas-batista.jpg',
            '8♣': '8-of-clubs-zutto.jpg',
            '9♣': '9-of-clubs-skinpop-studio.jpg',
            '10♣': '10-of-clubs-mike-creative-mints.jpg',
            'J♣': 'jack-of-clubs-yury-ustsinau.jpg',
            'Q♣': 'queen-of-clubs-raphael-vicenzi.jpg',
            'K♣': 'king-of-clubs-burak-senturk.jpg',
            'A♣': 'ace-of-clubs-andreas-preis.jpg',
            JOKER: 'joker-zombie-yeti.jpg',
            JOKER_2: 'joker-amrei-hofstatter.jpg'
        },
        cardArtists: {
            '2♠': 'Fictive Artist',
            '3♠': 'Steven Wilson',
            '4♠': 'Anton Repponen',
            '5♠': 'Gabriel Moreno',
            '6♠': 'Zansky',
            '7♠': 'Choco Toy',
            '8♠': 'Rubens Scarelli',
            '9♠': 'Pichet Rujivararat',
            '10♠': 'Marcelo Schultz',
            'J♠': 'Peter Donnelly',
            'Q♠': 'Sara Blake',
            'K♠': 'Yeaaah! Studio',
            'A♠': 'Ars Thanea',
            '2♥': 'Maria Grønlund',
            '3♥': 'Oscar Ramos',
            '4♥': 'Steve Simpson',
            '5♥': 'Charles Williams',
            '6♥': 'FREAK CITY',
            '7♥': 'Antoni Tudisco',
            '8♥': 'Van Orton Design',
            '9♥': 'Irina Vinnik',
            '10♥': 'David Sossella',
            'J♥': 'Julian Ardila',
            'Q♥': 'Orlando Arocena',
            'K♥': 'YoAz',
            'A♥': 'STUDIO BLUP',
            '2♦': 'Jon Lau',
            '3♦': 'Zipeng Zhu',
            '4♦': 'FOREAL™',
            '5♦': 'Patrick Seymour',
            '6♦': 'Ian Jepson',
            '7♦': 'Sakiroo',
            '8♦': 'marubu',
            '9♦': 'Viktor Miller-Gausa',
            '10♦': 'Kerby Rosanes',
            'J♦': 'Stavros Damos',
            'Q♦': 'Pablo Jurado Ruiz',
            'K♦': 'Alexis Marcou',
            'A♦': 'Joshua Davis',
            '2♣': 'Jonathan Calugi',
            '3♣': 'Tamer Köseli',
            '4♣': 'Jeff Rogers',
            '5♣': 'Mikey Burton',
            '6♣': 'MIGHTY SHORT',
            '7♣': 'Adhemas Batista',
            '8♣': 'Zutto',
            '9♣': 'Raul Urias',
            '10♣': 'Mike / Creative Mints',
            'J♣': 'Yury Ustsinau',
            'Q♣': 'Raphaël Vicenzi',
            'K♣': 'Burak Sentürk',
            'A♣': 'Andreas Preis',
            JOKER_1: 'Zombie Yeti',
            JOKER_2: 'Amrei Hofstätter'
        },
        // URL slug overrides for artists where filename doesn't match website URL
        cardArtistUrls: {
            '2♥': 'maria-grønlund',
            '3♣': 'tamer-köseli',
            '6♣': 'mighty-short',
            '7♠': 'choco-toy',
            '8♦': 'marubu',
            '9♣': 'raul-urias',
            'K♣': 'burak-sentürk',
            'Q♠': 'sara-blake',
            JOKER_2: 'amrei-hofstätter'
        }
    },
    three: {
        id: 'three',
        name: 'Edition Three',
        baseUrl: 'https://s3.amazonaws.com/img.playingarts.com/three-small-hd/',
        infoUrl: 'https://playingarts.com/three/',
        backsideImage: '_backside-juan-diaz-faes.jpg',
        cardFilenames: {
            '2♠': '2-of-spades-kate-ohara.jpg',
            '3♠': '3-of-spades-antonio-rodrigues-jr.jpg',
            '4♠': '4-of-spades-inkration-studio.jpg',
            '5♠': '5-of-spades-leandro-castelao.jpg',
            '6♠': '6-of-spades-charis-tsevis.jpg',
            '7♠': '7-of-spades-aj-frena.jpg',
            '8♠': '8-of-spades-mike-perry.jpg',
            '9♠': '9-of-spades-jackson-alves.jpg',
            '10♠': '10-of-spades-bratislav-milenkovic.jpg',
            'J♠': 'jack-of-spades-grzegorz-domaradzki.jpg',
            'Q♠': 'queen-of-spades-david-vicente.jpg',
            'K♠': 'king-of-spades-jonny-wan.jpg',
            'A♠': 'ace-of-spades-gmunk.jpg',
            '2♥': '2-of-hearts-wade-jeffree.jpg',
            '3♥': '3-of-hearts-dan-matutina.jpg',
            '4♥': '4-of-hearts-tobias-hall.jpg',
            '5♥': '5-of-hearts-bram-vanhaeren.jpg',
            '6♥': '6-of-hearts-man-tsun.jpg',
            '7♥': '7-of-hearts-velvet-spectrum.jpg',
            '8♥': '8-of-hearts-amaia-arrazola.jpg',
            '9♥': '9-of-hearts-will-scobie.jpg',
            '10♥': '10-of-hearts-daniel-shaffer.jpg',
            'J♥': 'jack-of-hearts-roman-klonek.jpg',
            'Q♥': 'queen-of-hearts-alessandro-pautasso.jpg',
            'K♥': 'king-of-hearts-denis-zilber.jpg',
            'A♥': 'ace-of-hearts-jesse-hernandez.jpg',
            '2♦': '2-of-dimonds-zooka.jpg',
            '3♦': '3-of-dimonds-burnt-toast-creative.jpg',
            '4♦': '4-of-dimonds-edgar-rozo.jpg',
            '5♦': '5-of-dimonds-leonardoworx.jpg',
            '6♦': '6-of-dimonds-francisco-miranda.jpg',
            '7♦': '7-of-diamonds-rafael-mayani.jpg',
            '8♦': '8-of-diamonds-pierre-kleinhouse.jpg',
            '9♦': '9-of-dimonds-ery-burns.jpg',
            '10♦': '10-of-dimonds-justin-maller.jpg',
            'J♦': 'jack-of-dimonds-alvaro-tapia-hidalgo.jpg',
            'Q♦': 'queen-of-dimonds-nicolle-florian.jpg',
            'K♦': 'king-of-dimonds-skinpop-studio.jpg',
            'A♦': 'ace-of-dimonds-joan-tarrago.jpg',
            '2♣': '2-of-clubs-riccardo-guasco.jpg',
            '3♣': '3-of-clubs-david-mcleod.jpg',
            '4♣': '4-of-clubs-victor-vergara.jpg',
            '5♣': '5-of-clubs-justin-poulter.jpg',
            '6♣': '6-of-clubs-middle-boop-gordon-reid.jpg',
            '7♣': '7-of-clubs-saddo.jpg',
            '8♣': '8-of-clubs-andreas-preis.jpg',
            '9♣': '9-of-clubs-karol-banach.jpg',
            '10♣': '10-of-clubs-jilipollo.jpg',
            'J♣': 'jack-of-clubs-mister-thoms.jpg',
            'Q♣': 'queen-of-clubs-nikita-kaun.jpg',
            'K♣': 'king-of-clubs-angga-tantama.jpg',
            'A♣': 'ace-of-clubs-omaraqil.jpg',
            JOKER: 'joker-1-blackout-brother.jpg',
            JOKER_2: 'joker-2-wes-art-studio.jpg'
        },
        cardArtists: {
            '2♠': 'Kate O\'Hara',
            '3♠': 'Antonio Rodrigues Jr',
            '4♠': 'Inkration Studio',
            '5♠': 'Leandro Castelao',
            '6♠': 'Charis Tsevis',
            '7♠': 'AJ Frena',
            '8♠': 'Mike Perry',
            '9♠': 'Jackson Alves',
            '10♠': 'Bratislav Milenkovic',
            'J♠': 'Grzegorz Domaradzki',
            'Q♠': 'D.Vicente',
            'K♠': 'Jonny Wan',
            'A♠': 'GMUNK',
            '2♥': 'Wade Jeffree',
            '3♥': 'Dan Matutina',
            '4♥': 'Tobias Hall',
            '5♥': 'Bram Vanhaeren',
            '6♥': 'Man-Tsun',
            '7♥': 'Velvet Spectrum',
            '8♥': 'Amaia Arrazola',
            '9♥': 'Will Scobie',
            '10♥': 'Daniel Shaffer',
            'J♥': 'Roman Klonek',
            'Q♥': 'Alessandro Pautasso',
            'K♥': 'Denis Zilber',
            'A♥': 'Jesse Hernandez',
            '2♦': 'Zooka',
            '3♦': 'Burnt Toast Creative',
            '4♦': 'Edgar Rozo',
            '5♦': 'Leonardoworx',
            '6♦': 'Francisco Miranda',
            '7♦': 'Rafael Mayani',
            '8♦': 'Pierre Kleinhouse',
            '9♦': 'Ery Burns',
            '10♦': 'Justin Maller',
            'J♦': 'Alvaro Tapia Hidalgo',
            'Q♦': 'Nicolle Florian',
            'K♦': 'Raul Urias',
            'A♦': 'Joan Tarragó',
            '2♣': 'Riccardo Guasco',
            '3♣': 'David McLeod',
            '4♣': 'Victor Vergara',
            '5♣': 'Justin Poulter',
            '6♣': 'Middle Boop (Gordon Reid)',
            '7♣': 'Saddo',
            '8♣': 'Andreas Preis',
            '9♣': 'Karol Banach',
            '10♣': 'Javier Medellin Puyou',
            'J♣': 'Mister Thoms',
            'Q♣': 'Nikita Kaun',
            'K♣': 'Angga Tantama',
            'A♣': 'Omar Aqil',
            JOKER_1: 'Blackout Brother',
            JOKER_2: 'Wes Art Studio'
        },
        cardArtistUrls: {
            '6♣': 'middle-boop',
            'A♦': 'joan-tarragó',
            'K♦': 'raul-urias',
            'Q♠': 'd.vicente'
        }
    }
};

// List of available edition IDs for random selection
export const EDITION_IDS = Object.keys(EDITIONS);

/**
 * Get a random edition (different from current)
 * @returns {Object} Random edition config
 */
export function getRandomEdition() {
    // Filter out the current edition to ensure rotation
    const availableIds = EDITION_IDS.filter((id) => id !== currentEdition.id);
    const randomIndex = Math.floor(Math.random() * availableIds.length);
    return EDITIONS[availableIds[randomIndex]];
}

/**
 * Get edition by ID
 * @param {string} editionId - Edition identifier (one, two, three)
 * @returns {Object} Edition config
 */
export function getEdition(editionId) {
    return EDITIONS[editionId] || EDITIONS.one;
}

// Current edition state (will be set on game start)
let currentEdition = EDITIONS.one;

/**
 * Set the current edition
 * @param {Object} edition - Edition config
 */
export function setCurrentEdition(edition) {
    currentEdition = edition;
}

/**
 * Get the current edition
 * @returns {Object} Current edition config
 */
export function getCurrentEdition() {
    return currentEdition;
}
